import type { Project, ProjectStatus, Role } from './types'

export const workflow: Array<{ status: ProjectStatus; label: string; owner: string; optional?: boolean }> = [
  { status: 'request', label: '요청', owner: '요청자' },
  { status: 'dept_review', label: '승인', owner: '승인자' },
  { status: 'srs', label: 'SRS', owner: '기획' },
  { status: 'sds', label: 'SDS', owner: '기획/개발' },
  { status: 'schedule', label: '개발 준비/일정 확정', owner: 'PM' },
  { status: 'development', label: '개발', owner: '개발' },
  { status: 'qc_security', label: 'QC/보안', owner: '품질/보안', optional: true },
  { status: 'uat', label: 'UAT', owner: '요청자', optional: true },
  { status: 'completion', label: '완료보고', owner: 'PM' },
  { status: 'published', label: '게시', owner: '시스템' },
]

export const roleLabels: Record<Role, string> = {
  requester: '요청자',
  pm: 'PM',
  cem: 'CEM',
  developer: '개발자',
  infra: '인프라',
  qa: 'QC',
  security: '보안',
  patent: '특허',
  admin: '관리자',
}

export const demoProjects: Project[] = [
  {
    id: '1',
    code: 'PRJ-2505-001',
    requestType: 'new_feature',
    title: '모바일 앱 푸시 알림 기능 추가',
    serviceName: '모바일 앱',
    serviceArea: '마케팅 알림/CRM',
    requester: '이영업',
    ownerTeam: '마케팅',
    priority: 'high',
    status: 'dept_review',
    summary: 'iOS/Android 앱에 마케팅 푸시 알림 발송과 예약 발송 기능을 추가합니다.',
    currentProblem: '캠페인 알림을 앱 외부 채널에 의존해 전환율 측정과 예약 발송이 어렵습니다.',
    desiredOutcome: '앱에서 대상별 푸시 알림을 예약 발송하고 발송 결과를 확인합니다.',
    successMetric: '캠페인 푸시 발송 성공률 98% 이상, 예약 발송 오차 5분 이내',
    affectedUsers: '마케팅 운영자, iOS/Android 앱 사용자',
    dueDate: '2026-05-24',
    createdAt: '2026-05-15',
    updatedAt: '2026-05-17T09:10:00+09:00',
    risk: '광고성 정보 수신동의 문구 검토 필요',
    progress: 18,
    nextAction: '마케팅/법무 검토 의견 취합',
    assigneeRole: 'pm',
    workflowConfig: { requiresQcSecurity: true, requiresUat: true },
    approvalState: {
      requiredRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
      approvedRoles: ['pm', 'cem'],
    },
    securityReview: {
      dataClassification: '앱 사용자 푸시 수신 대상 정보와 발송 이력 포함, 민감정보 없음',
      accessScope: '마케팅 운영자와 관리자만 발송/조회 가능, 일반 사용자는 수신만 가능',
      externalExposure: 'FCM/APNs로 푸시 발송, 외부 마케팅 도구 연동은 없음',
      storagePolicy: '발송 이력과 대상 로그는 내부 DB에 저장, 운영 로그 90일 보관',
      securityNotes: '수신 동의 여부 검증, 관리자 권한 분리, 발송 이력 감사 로그 필요',
    },
    tasks: [
      { id: 't1', title: '수신 동의 문구 검토', owner: '법무', dueDate: '2026-05-18', status: 'doing' },
      { id: 't2', title: '발송 대상 세그먼트 정의', owner: '마케팅', dueDate: '2026-05-19', status: 'todo' },
    ],
    logs: [
      { id: 'l1', at: '2026-05-17 09:10', actor: '김검토', message: '법무 검토 태스크를 추가했습니다.' },
      { id: 'l2', at: '2026-05-15 19:16', actor: '이영업', message: '신규 요청을 등록했습니다.' },
    ],
  },
  {
    id: '2',
    code: 'PRJ-2505-002',
    requestType: 'integration_api',
    title: 'B2B 파트너 전용 API 포털 구축',
    serviceName: '파트너 API',
    serviceArea: 'B2B 연동/개발자 포털',
    requester: '이영업',
    ownerTeam: '영업',
    priority: 'normal',
    status: 'sds',
    summary: '외부 파트너사가 자체 API를 테스트하고 문서를 확인할 수 있는 포털을 구축합니다.',
    currentProblem: '파트너사가 API 문서와 테스트 계정을 매번 영업 담당자에게 요청하고 있습니다.',
    desiredOutcome: '파트너사가 직접 문서, 샌드박스 키, 호출 이력을 확인합니다.',
    successMetric: '파트너 API 문의 40% 감소, 샌드박스 키 발급 리드타임 1일 이내',
    affectedUsers: 'B2B 파트너 개발자, 영업 담당자, 내부 API 운영자',
    dueDate: '2026-06-05',
    createdAt: '2026-05-15',
    updatedAt: '2026-05-17T09:58:00+09:00',
    risk: '인증 방식 확정 전까지 개발 산출물이 흔들릴 수 있음',
    progress: 36,
    nextAction: 'SDS 초안 작성 완료',
    assigneeRole: 'developer',
    workflowConfig: { requiresQcSecurity: true, requiresUat: false },
    approvalState: {
      requiredRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
      approvedRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
    },
    securityReview: {
      dataClassification: '파트너 계정 정보와 API 호출 이력 포함, 민감정보 없음',
      accessScope: '파트너 관리자와 내부 운영자만 계정/키 관리 가능',
      externalExposure: '외부 파트너 개발자가 포털과 API 문서를 조회하고 샌드박스 키를 발급받음',
      storagePolicy: 'API 키와 호출 이력 저장, 키 재발급 정책과 만료 정책 필요',
      securityNotes: 'OAuth 인증, API 키 노출 방지, 파트너별 접근 분리 정책 검토 필요',
    },
    tasks: [
      { id: 't3', title: 'OAuth 플로우 결정', owner: '개발', dueDate: '2026-05-20', status: 'doing' },
      { id: 't4', title: '파트너 샌드박스 권한표 작성', owner: '영업', dueDate: '2026-05-22', status: 'todo' },
    ],
    logs: [
      { id: 'l3', at: '2026-05-17 09:58', actor: '박개발', message: 'SRS를 승인하고 SDS 단계로 이동했습니다.' },
      { id: 'l4', at: '2026-05-16 14:20', actor: '이영업', message: '파트너사 샘플 계정 요구사항을 첨부했습니다.' },
    ],
  },
  {
    id: '3',
    code: 'PRJ-2505-003',
    requestType: 'improvement',
    title: '정산 자동화 시스템 개선',
    serviceName: '정산 백오피스',
    serviceArea: '정산/세금계산서',
    requester: '최운영',
    ownerTeam: '운영',
    priority: 'urgent',
    status: 'development',
    summary: '수동 정산 프로세스를 자동화하고 세금계산서 발행 및 정산 리포트를 생성합니다.',
    currentProblem: '월말 정산 시 엑셀 수작업이 많아 검증 누락과 재작업이 반복됩니다.',
    desiredOutcome: '정산 대상 집계, 예외 확인, 세금계산서 발행 파일 생성을 자동화합니다.',
    successMetric: '월말 정산 작업 시간 60% 절감, 수기 오류 0건',
    affectedUsers: '운영팀, 재무팀, 파트너 정산 담당자',
    dueDate: '2026-05-21',
    createdAt: '2026-05-12',
    updatedAt: '2026-05-17T11:30:00+09:00',
    risk: '레거시 정산 데이터 샘플 부족',
    progress: 58,
    nextAction: '정산 예외 케이스 API 구현',
    assigneeRole: 'developer',
    workflowConfig: { requiresQcSecurity: false, requiresUat: false },
    approvalState: {
      requiredRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
      approvedRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
    },
    securityReview: {
      dataClassification: '파트너 정산 데이터와 세금계산서 관련 정보 포함',
      accessScope: '운영팀/재무팀 중심, 정산 예외 처리 권한 분리 필요',
      externalExposure: '외부 반출은 정산 파일 다운로드 수준, 별도 외부 API 연동은 제한적',
      storagePolicy: '정산 파일과 로그 보관 필요, 회계 감사용 보존 기간 확인 필요',
      securityNotes: '다운로드 권한 통제, 정산 로그 추적, 파일 보관 기간 검토 필요',
    },
    tasks: [
      { id: 't5', title: '정산 예외 케이스 API', owner: '개발', dueDate: '2026-05-18', status: 'doing' },
      { id: 't6', title: '샘플 데이터 30건 확보', owner: '운영', dueDate: '2026-05-17', status: 'blocked' },
      { id: 't7', title: '회계 검증 시나리오', owner: '재무', dueDate: '2026-05-20', status: 'todo' },
    ],
    logs: [
      { id: 'l5', at: '2026-05-17 11:30', actor: '박개발', message: '레거시 데이터 누락으로 일부 작업을 보류했습니다.' },
      { id: 'l6', at: '2026-05-15 10:12', actor: '최운영', message: '긴급 우선순위로 상향했습니다.' },
    ],
  },
  {
    id: '4',
    code: 'PRJ-2505-004',
    requestType: 'integration_api',
    title: '신규 결제 PG 연동 (토스페이먼츠)',
    serviceName: '결제 서비스',
    serviceArea: 'PG/체크아웃',
    requester: '이영업',
    ownerTeam: '영업',
    priority: 'high',
    status: 'qc_security',
    summary: '기존 KG이니시스에서 토스페이먼츠로 전환하고 카드/계좌이체/간편결제를 모두 지원합니다.',
    currentProblem: '기존 PG 장애 대응과 간편결제 확장이 느려 신규 제휴 매출 기회가 지연됩니다.',
    desiredOutcome: '토스페이먼츠 결제 수단을 추가하고 결제/취소/웹훅 흐름을 안정화합니다.',
    successMetric: '결제 성공률 99.5% 이상, 결제 장애 자동 알림 1분 이내',
    affectedUsers: '구매 고객, 영업팀, 결제 운영자',
    dueDate: '2026-05-28',
    createdAt: '2026-05-15',
    updatedAt: '2026-05-17T10:42:00+09:00',
    risk: '보안 검사 결과가 늦어지면 UAT 일정 영향',
    progress: 72,
    nextAction: 'QC와 보안 검사 결과 입력',
    assigneeRole: 'qa',
    workflowConfig: { requiresQcSecurity: true, requiresUat: true },
    approvalState: {
      requiredRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
      approvedRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
    },
    securityReview: {
      dataClassification: '결제 시도/성공/실패 정보와 웹훅 로그 포함',
      accessScope: '결제 운영자와 개발자 중심, 민감 결제정보 직접 저장은 없음',
      externalExposure: '토스페이먼츠 API 및 웹훅 연동, 외부 PG와 통신',
      storagePolicy: '결제 로그와 오류 로그 저장, 서명 검증 로그 보관 필요',
      securityNotes: '웹훅 서명 검증, 결제 실패 로그 마스킹, 운영자 권한 분리 필요',
    },
    tasks: [
      { id: 't8', title: '결제 성공/실패 케이스 QC', owner: 'QC', dueDate: '2026-05-18', status: 'doing' },
      { id: 't9', title: '웹훅 서명 검증', owner: '보안', dueDate: '2026-05-18', status: 'todo' },
    ],
    logs: [
      { id: 'l7', at: '2026-05-17 10:42', actor: '한QC', message: 'QC/보안 동시 검사를 시작했습니다.' },
      { id: 'l8', at: '2026-05-16 18:03', actor: '박개발', message: '개발 산출물을 제출했습니다.' },
    ],
  },
  {
    id: '5',
    code: 'PRJ-2505-005',
    requestType: 'policy_change',
    title: 'AI 챗봇 고객센터 전면 교체',
    serviceName: '고객센터',
    serviceArea: '상담 자동화',
    requester: '김CX',
    ownerTeam: '고객센터',
    priority: 'low',
    status: 'rejected',
    summary: '기존 상담원을 AI로 100% 대체하는 고객센터 프로젝트입니다.',
    currentProblem: '피크 시간대 상담 대기 시간이 길지만 자동화 적용 범위가 정의되지 않았습니다.',
    desiredOutcome: '단순 문의 자동 응대 범위를 정하고 상담원 전환 기준을 명확히 합니다.',
    successMetric: '단순 문의 자동 응대율 30%, 상담원 전환 실패율 2% 이하',
    affectedUsers: '고객센터 상담원, 최종 고객, CX 운영자',
    dueDate: '2026-06-12',
    createdAt: '2026-05-15',
    updatedAt: '2026-05-16T16:00:00+09:00',
    risk: '운영 정책과 고객 고지 범위가 불명확함',
    progress: 8,
    nextAction: '범위 축소 후 재요청 필요',
    assigneeRole: 'requester',
    workflowConfig: { requiresQcSecurity: false, requiresUat: true },
    approvalState: {
      requiredRoles: ['pm', 'cem', 'security', 'infra', 'qa', 'patent', 'admin'],
      approvedRoles: ['pm'],
    },
    securityReview: {
      dataClassification: '상담 이력과 고객 문의 데이터 포함 가능',
      accessScope: '고객센터 운영자와 AI 운영자 중심, 상담원 전환 권한 정책 필요',
      externalExposure: '외부 AI/챗봇 서비스 연동 가능성 있음',
      storagePolicy: '상담 로그 보관 정책과 개인정보 마스킹 기준 확인 필요',
      securityNotes: '개인정보 처리 위탁, 대화 로그 저장 범위, 모델 학습 반영 여부 검토 필요',
    },
    tasks: [{ id: 't10', title: '대체 범위 재정의', owner: '고객센터', dueDate: '2026-05-22', status: 'todo' }],
    logs: [
      { id: 'l9', at: '2026-05-16 16:00', actor: '김검토', message: '범위 과다 및 정책 미비로 반려했습니다.' },
    ],
  },
]
